### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Drapersniper** [Honkertonken/Honkertonken-Cogs#16]
So I won't ask you to remove the cog, that being said 

1. to use someone else work you should ask for permission first and if you cant get permission you cant use it.

2. My cog is unlicensed therefore you are not allowed to publish under the MIT license.

your option is fixed 2 so that the MIA or any future license does not apply to my cog, if you are unable to do that I'm not willing to allow my work to be left here.

**Comment by Honkertonken** [comment]
Hey draper ~~big fan btw~~, 
Sorry for the inconvenience this was just plain stupid on my part. i shall be removing the cog in a whole mainly because I haven't really done anything on it. 
Thanks for cooperating.
